# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  
  pool:
    vmImage: 'ubuntu-latest'
  
  jobs:
  - job: Job1
    steps:
    - script: echo One line script without pipe - Job1
      displayName: 'Run a one-line script - Job1'
  
  - job: Job2
    dependsOn: Job1
    steps:
    - script: echo One line script without pipe - Job2
      displayName: 'Run a multi-line script - Job2'
      
  - job: Job3
    dependsOn: Job2
    steps:
    - script: echo One line script without pipe - Job3
      displayName: 'Run a multi-line script - Job3'