trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJobInTheBuild
    steps:
    - bash: echo Build First Job
  - job: SecondJobInTheBuild
    steps:
    - bash: echo Build Second Job
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob